about:
  name: WASP Example
  dir: inc # location of this file relative to the file root

text_domain: WASP

post_types:
  events:
    labels:
      singular_name: Event
    taxonomies:
      - custom_tax1
      - custom_tax2

  jobs:
    labels:
      singular_name: Job

image_sizes:
  hero:
    width: 1000
    height: 300
  headshot:
    width: 400
    height: 400
    crop: [right, top]

constants:
  WP_DEBUG: true

site_options:
  blogname: My Blog!!

menu_locations:
  primary: Primary Menu
  footer: Footer Menu

autoloader:
  namespace: OomphInc\Project

theme_supports:
  - post-thumbnails
  - html5:
      - [search-form, comment-form, comment-list]
      - argument 2

widget_areas:
  before-footer:
    name: Before footer
    before_widget: <div id="%1$s" class="widget %2$s">
    after_widget: </div>

includes:
  use: include
  files: # relative to file root
    - foo.php
    - bar.php
    - inc/:
      - file1.php
      - file2.php
      - sub:
        - file4.php
  files_match: inc/*.php
