version: 3.4

post_types:
  events:
    labels:
      singular_name: Event
    taxonomies:
      - custom_tax1
      - custom_tax2

  jobs:
    labels:
      singular_name: Job

image_sizes:
  hero:
    width: 1000
    height: 300
  headshot:
    width: 400
    height: 400
    crop: [right, top]

constants:
  WP_DEBUG: true

site_options:
  blogname: My Blog!!

menu_locations:
  primary: Primary Menu
  footer: Footer Menu

text_domain: FAST_WP

autoloader:
  namespace: OomphInc\Project
