version: 3.4

post_types:
  default:
    args:

  events:
    args:
      label: foo
      labels:
        label1: bar
        label2: baz

  custom2:
    args:

image_sizes:
  hero:
    width: 1000
    height: 300
  headshot:
    width: 400
    height: 400
    crop: [right, top]

constants:
  WP_DEBUG: true

site_options:
  blogname: My Blog!!

menu_locations:
  primary: Primary Menu
  footer: Footer Menu

text_domain: FAST_WP
