version: 3.4
post_types:
  default:
    args:

  events:
    args:
      label: foo
      labels:
        label1: bar
        label2: baz

  custom2:
    args:
image_sizes:
  hero:
    width: 1000
    height: 300
    crop: true
  headshot:
    width: 400
    height: 400
    crop: [right, top]
